### ISSUE TITLE
Support for Kodi 20

### ISSUE THREAD

**Issue by berti34** [zosky/kodi.context.tags#6]
Any chance this will get updated to support Kodi 20 Nexus?

**Comment by thlucas1** [comment]
I can't speak for zosky, but I will be probably be updating [my version](https://github.com/thlucas1/kodi.context.tags) of this Add-On.  I forked zosky's original repository in 2018 and have been supporting it ever since.  I have not installed Kodi 20 Nexus as of yet, so not sure how much effort it will be.  Will keep you posted.
Thanks - Todd

**Comment by berti34** [comment]
Thank you so much! I will try it soon.

**Comment by thlucas1** [comment]
> Thank you so much! I will try it soon.

I was able to install the Kodi 20 Nexus pre-release build on my test machine earlier today, and verified that my version of the manageTags Add-On works fine with it.  You will need to download the installer from [my repository](https://github.com/thlucas1/kodi.context.tags) though, as the installer on zosky's repository is outdated and no longer maintained.  Check out the "[Download and Install](https://github.com/thlucas1/kodi.context.tags)" section for a link to the installer.

Hope it helps!

Thanks - Todd
